postgres:
  build: applications/postgres
  ports:
    - "5432:5432"

flaskapp:
  build: applications/flaskapp
  command: "python3 hello.py"
  links:
    - postgres
  volumes:
    - /vagrant/applications/flaskapp:/opt/flaskapp

proxy:
  build: applications/proxy
  ports:
    - "80:80"
  volumes:
    - /vagrant/proxy/sites-enabled:/etc/nginx/sites-enabled
  links:
    - flaskapp
